name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install dependencies with --legacy-peer-deps
        run: npm install --legacy-peer-deps

      # - name: Run lint  # Dòng này sẽ bị bỏ qua
      #   run: npm run lint  # Dòng này sẽ bị bỏ qua

      # - name: Build project
      #   run: npm run build --no-lint

      # Tạo file .env từ GitHub Secrets
      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env
          echo "NEXT_PUBLIC_CLIENT_URL=${{ secrets.NEXT_PUBLIC_CLIENT_URL }}" >> .env
          echo "NEXT_PUBLIC_SOCKET_URL=${{ secrets.NEXT_PUBLIC_SOCKET_URL }}" >> .env
          echo "NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL }}" >> .env

      # Build Docker image và copy .env vào container
      - name: Build Docker image
        run: |
          docker build --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
                       --build-arg NEXT_PUBLIC_CLIENT_URL=${{ secrets.NEXT_PUBLIC_CLIENT_URL }} \
                       --build-arg NEXT_PUBLIC_SOCKET_URL=${{ secrets.NEXT_PUBLIC_SOCKET_URL }} \
                       --build-arg NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL }} \
                       -t ebai-fe .

      # Đăng nhập vào Docker Hub và push image
      - name: Login to Docker Hub with Token
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Tag Docker image with version
        run: |
          docker tag ebai-fe ${{ secrets.DOCKER_USERNAME }}/ebai-fe:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ebai-fe:latest

      - name: Connect to VM and pull Docker image
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22  # Cổng mặc định SSH
          script: |
            # Kéo image từ Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/ebai-fe:latest

            # Chạy container từ image đã pull về
            docker run -d -p 80:5001 ${{ secrets.DOCKER_USERNAME }}/ebai-fe:latest
